// ===== JUZ 'AMMA DATA - Surah 78 to 114 =====
// Complete metadata for all 37 surahs with updated audio file names

const juzAmmaData = [
    {
        id: 78,
        surahNumber: 78,
        arabicName: "النبأ",
        englishName: "An-Naba'",
        englishTranslation: "The Great News",
        ayahCount: 40,
        revelation: "Makki",
        audioFile: "A-Naba-u.mp3",
        difficulty: "Medium",
        memorized: false,
        progress: 0
    },
    {
        id: 79,
        surahNumber: 79,
        arabicName: "النازعات",
        englishName: "An-Nazi'at",
        englishTranslation: "Those Who Drag Forth",
        ayahCount: 46,
        revelation: "Makki",
        audioFile: "A-Naaziah.mp3",
        difficulty: "Medium",
        memorized: false,
        progress: 0
    },
    {
        id: 80,
        surahNumber: 80,
        arabicName: "عبس",
        englishName: "'Abasa",
        englishTranslation: "He Frowned",
        ayahCount: 42,
        revelation: "Makki",
        audioFile: "Abasa.mp3",
        difficulty: "Medium",
        memorized: false,
        progress: 0
    },
    {
        id: 81,
        surahNumber: 81,
        arabicName: "التكوير",
        englishName: "At-Takwir",
        englishTranslation: "The Overthrowing",
        ayahCount: 29,
        revelation: "Makki",
        audioFile: "A-Takwir.mp3",
        difficulty: "Medium",
        memorized: false,
        progress: 0
    },
    {
        id: 82,
        surahNumber: 82,
        arabicName: "الإنفطار",
        englishName: "Al-Infitar",
        englishTranslation: "The Cleaving",
        ayahCount: 19,
        revelation: "Makki",
        audioFile: "Al-Infitwaar.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 83,
        surahNumber: 83,
        arabicName: "المطففين",
        englishName: "Al-Mutaffifin",
        englishTranslation: "The Defrauding",
        ayahCount: 36,
        revelation: "Makki",
        audioFile: "Al-Mutwafifin.mp3",
        difficulty: "Medium",
        memorized: false,
        progress: 0
    },
    {
        id: 84,
        surahNumber: 84,
        arabicName: "الإنشقاق",
        englishName: "Al-Inshiqaq",
        englishTranslation: "The Splitting Open",
        ayahCount: 25,
        revelation: "Makki",
        audioFile: "Al-Inshiqaq.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 85,
        surahNumber: 85,
        arabicName: "البروج",
        englishName: "Al-Buruj",
        englishTranslation: "The Constellations",
        ayahCount: 22,
        revelation: "Makki",
        audioFile: "Al-Burudji.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 86,
        surahNumber: 86,
        arabicName: "الطارق",
        englishName: "At-Tariq",
        englishTranslation: "The Nightcomer",
        ayahCount: 17,
        revelation: "Makki",
        audioFile: "At-Twariq.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 87,
        surahNumber: 87,
        arabicName: "الأعلى",
        englishName: "Al-A'la",
        englishTranslation: "The Most High",
        ayahCount: 19,
        revelation: "Makki",
        audioFile: "Al-Aala.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 88,
        surahNumber: 88,
        arabicName: "الغاشية",
        englishName: "Al-Ghashiyah",
        englishTranslation: "The Overwhelming",
        ayahCount: 26,
        revelation: "Makki",
        audioFile: "Al-Ghashiyah.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 89,
        surahNumber: 89,
        arabicName: "الفجر",
        englishName: "Al-Fajr",
        englishTranslation: "The Dawn",
        ayahCount: 30,
        revelation: "Makki",
        audioFile: "Al-Fajri.mp3",
        difficulty: "Medium",
        memorized: false,
        progress: 0
    },
    {
        id: 90,
        surahNumber: 90,
        arabicName: "البلد",
        englishName: "Al-Balad",
        englishTranslation: "The City",
        ayahCount: 20,
        revelation: "Makki",
        audioFile: "Al-Balad.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 91,
        surahNumber: 91,
        arabicName: "الشمس",
        englishName: "Ash-Shams",
        englishTranslation: "The Sun",
        ayahCount: 15,
        revelation: "Makki",
        audioFile: "A-Shams.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 92,
        surahNumber: 92,
        arabicName: "الليل",
        englishName: "Al-Layl",
        englishTranslation: "The Night",
        ayahCount: 21,
        revelation: "Makki",
        audioFile: "A-Layl.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 93,
        surahNumber: 93,
        arabicName: "الضحى",
        englishName: "Ad-Duha",
        englishTranslation: "The Morning Brightness",
        ayahCount: 11,
        revelation: "Makki",
        audioFile: "A-Dwuhaa.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 94,
        surahNumber: 94,
        arabicName: "الشرح",
        englishName: "Ash-Sharh",
        englishTranslation: "The Relief",
        ayahCount: 8,
        revelation: "Makki",
        audioFile: "A-Sharh.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 95,
        surahNumber: 95,
        arabicName: "التين",
        englishName: "At-Tin",
        englishTranslation: "The Fig",
        ayahCount: 8,
        revelation: "Makki",
        audioFile: "At-Tiin.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 96,
        surahNumber: 96,
        arabicName: "العلق",
        englishName: "Al-'Alaq",
        englishTranslation: "The Clot",
        ayahCount: 19,
        revelation: "Makki",
        audioFile: "Al-Alaq.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 97,
        surahNumber: 97,
        arabicName: "القدر",
        englishName: "Al-Qadr",
        englishTranslation: "The Decree",
        ayahCount: 5,
        revelation: "Makki",
        audioFile: "Al-Qadri.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 98,
        surahNumber: 98,
        arabicName: "البينة",
        englishName: "Al-Bayyinah",
        englishTranslation: "The Clear Proof",
        ayahCount: 8,
        revelation: "Madani",
        audioFile: "Al-Bayyinah.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 99,
        surahNumber: 99,
        arabicName: "الزلزلة",
        englishName: "Az-Zalzalah",
        englishTranslation: "The Earthquake",
        ayahCount: 8,
        revelation: "Madani",
        audioFile: "Az-Zilzalah.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 100,
        surahNumber: 100,
        arabicName: "العاديات",
        englishName: "Al-'Adiyat",
        englishTranslation: "The Courser",
        ayahCount: 11,
        revelation: "Makki",
        audioFile: "Al-Adiyah.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 101,
        surahNumber: 101,
        arabicName: "القارعة",
        englishName: "Al-Qari'ah",
        englishTranslation: "The Calamity",
        ayahCount: 11,
        revelation: "Makki",
        audioFile: "Al-Qaariah.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 102,
        surahNumber: 102,
        arabicName: "التكاثر",
        englishName: "At-Takathur",
        englishTranslation: "Competition",
        ayahCount: 8,
        revelation: "Makki",
        audioFile: "At-Takaathur.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 103,
        surahNumber: 103,
        arabicName: "العصر",
        englishName: "Al-'Asr",
        englishTranslation: "The Time",
        ayahCount: 3,
        revelation: "Makki",
        audioFile: "Al-Asr.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 104,
        surahNumber: 104,
        arabicName: "الهمزة",
        englishName: "Al-Humazah",
        englishTranslation: "The Slanderer",
        ayahCount: 9,
        revelation: "Makki",
        audioFile: "Al-Humazah.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 105,
        surahNumber: 105,
        arabicName: "الفيل",
        englishName: "Al-Fil",
        englishTranslation: "The Elephant",
        ayahCount: 5,
        revelation: "Makki",
        audioFile: "Al-Fiil.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 106,
        surahNumber: 106,
        arabicName: "قريش",
        englishName: "Quraysh",
        englishTranslation: "Quraysh",
        ayahCount: 4,
        revelation: "Makki",
        audioFile: "Al-Quraysh.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 107,
        surahNumber: 107,
        arabicName: "الماعون",
        englishName: "Al-Ma'un",
        englishTranslation: "Small Kindnesses",
        ayahCount: 7,
        revelation: "Makki",
        audioFile: "Al-Mauun.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 108,
        surahNumber: 108,
        arabicName: "الكوثر",
        englishName: "Al-Kawthar",
        englishTranslation: "Abundance",
        ayahCount: 3,
        revelation: "Makki",
        audioFile: "Al-Kawthar.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 109,
        surahNumber: 109,
        arabicName: "الكافرون",
        englishName: "Al-Kafirun",
        englishTranslation: "The Disbelievers",
        ayahCount: 6,
        revelation: "Makki",
        audioFile: "Al-Kafirun.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 110,
        surahNumber: 110,
        arabicName: "النصر",
        englishName: "An-Nasr",
        englishTranslation: "The Divine Help",
        ayahCount: 3,
        revelation: "Madani",
        audioFile: "A-Nasr.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 111,
        surahNumber: 111,
        arabicName: "المسد",
        englishName: "Al-Masad",
        englishTranslation: "The Palm Fiber",
        ayahCount: 5,
        revelation: "Makki",
        audioFile: "Al-Masad.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 112,
        surahNumber: 112,
        arabicName: "الإخلاص",
        englishName: "Al-Ikhlas",
        englishTranslation: "Sincerity",
        ayahCount: 4,
        revelation: "Makki",
        audioFile: "Al-Ikhlas.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 113,
        surahNumber: 113,
        arabicName: "الفلق",
        englishName: "Al-Falaq",
        englishTranslation: "The Daybreak",
        ayahCount: 5,
        revelation: "Makki",
        audioFile: "Al-Falaq.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    },
    {
        id: 114,
        surahNumber: 114,
        arabicName: "الناس",
        englishName: "An-Nas",
        englishTranslation: "Mankind",
        ayahCount: 6,
        revelation: "Makki",
        audioFile: "A-Naas.mp3",
        difficulty: "Easy",
        memorized: false,
        progress: 0
    }
];

// Export to window
window.juzAmmaData = juzAmmaData;
console.log('✅ Juz Amma data loaded:', juzAmmaData.length, 'surahs');